version: "3.8"

services:
  Frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    environment:
      URI: URI #mention the backend URI
    depends_on:
      - backend

  Backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: URI #mention the mongodb connection url
      NODE_ENV: "development"
      PORT: 5000
      URI: URI #mention the backend URI
      JWT_SECRET_KEY: "j12n%^&3"
      JWT_EXPIRE: 50m
      RESET_PASSWORD_EXPIRE: 360000
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    # ports:
    #   - "27017:27017"
